### ISSUE TITLE
v0.5 - Can not deploy third party node module like mysql

### ISSUE THREAD

**Issue by nirmalgoswami** [serverless/serverless#897]
i am trying to use mysql module in code

mysql module is located in `parent_folder_of_all_lambda_function/node_modules` folder

i am using that module in `parent_folder_of_all_lambda_function/lib/database.js`

if we want to deploy folder/files which will use in all lambda function we need to change handler,i know this and i have changed handler value like ` "handler": "function_name(folder_name)/handler.handler",`

But i can not deploy `node_modules` folder i got `Cannot find module 'mysql'` error

in old version `0.4` i was able to check which files have been deployed in meta folder but my another question is how to check deployed files in `0.5`

**Comment by HyperBrain** [comment]
You could add the `-t` flag to `function deploy` that will keep the `_meta/tmp` for debugging.

**Comment by vbuser2004** [comment]
Having the same issue but with a different npm package. After upgrading to 0.5.1 the node_modules folder will not upload with the function. Used the -t flag and verified that the folder was not included. This dependency is listed in the package.json file.

**Comment by ac360** [comment]
@nirmalgoswami's issue might be related to using the Optimizer plugin, since that utilizes browserify and browserify may not work with `mysql`.

@vbuser2004 Could you provide some more details around your problem?  Have you tried the `-t` flag after `sls function deploy`?

**Comment by nirmalgoswami** [comment]
@ac360 it was working with serverless version `0.4.2` then it should work work with `0.5.1`

**Comment by andersdn** [comment]
@nirmalgoswami whilst it's not ideal to have multiple sets of node_modules, does the following work for you: Add a package.json within `parent_folder_of_all_lambda_function/lamba_fn/` and then install your node modules in the sub folder (same as <0.5, but the handler is no longer in a sub folder)

**Comment by vbuser2004** [comment]
@ac360   Yes, I used the -t flag. The resulting zip file does not include the node_modules folder at all. When using this flag I didn't know if there was a log I could review, but I did not locate any. If there is I will post it for your review. My package.json file had only 1 dependency - mailgun-js.

My project structure has the functions in different folders (like in the sls docs sample) with the node_modules folder in the main folder along with the package.json. 

As @andersdn stated, should we have a package.json and node_modules folder for each function? I didn't test that as it sounds like a lot of duplication of code, updates, etc.

Thank you!

**Comment by eahefnawy** [comment]
@vbuser2004 could you show us your directory structure? and also the `s-function.json` of that lambda function?

**Comment by vbuser2004** [comment]
I attached a detailed directory structure, and listed a less-verbose one below. 

The s-function.json file is also copied below. When I manually include the node_modules folder in the zip file and upload it myself, the function works as designed. 

**Directory:**
```
contactForm
  |--admin.env
  |--node_modules
  |------(all node_modules folders & files)
  |--package.json
  |--s-project.json
  |--s-resources-cf.json
  |--sendRequest
  |------event.json
  |------s-function.json
  |------s-template.json
  |------lib
  |--_meta
  |------resources
  |------variables
  |------_tmp
```

**s-function.json:**

```
{
  "name": "sendRequest",
  "runtime": "nodejs",
  "description": "Serverless Lambda function for project: contactForm",
  "customName": false,
  "customRole": false,
  "handler": "handler.handler",
  "timeout": 6,
  "memorySize": 1024,
  "authorizer": {},
  "custom": {
    "excludePatterns": []
  },
  "endpoints": [
    {
      "path": "sendRequest",
      "method": "POST",
      "type": "AWS",
      "authorizationType": "none",
      "authorizerFunction": false,
      "apiKeyRequired": false,
      "requestParameters": {},
      "requestTemplates": "$${apiRequestTemplate}",
      "responses": {
        "400": {
          "statusCode": "400"
        },
        "default": {
          "statusCode": "200",
          "responseParameters": {
            "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,Cache-Control'",
            "method.response.header.Access-Control-Allow-Methods": "'*'",
            "method.response.header.Access-Control-Allow-Origin": "'*'"
          },
          "responseModels": {},
          "responseTemplates": {
            "application/json": ""
          }
        }
      }
    },
    {
      "path": "sendRequest",
      "method": "OPTIONS",
      "type": "AWS",
      "authorizationType": "none",
      "authorizerFunction": false,
      "apiKeyRequired": false,
      "requestParameters": {},
      "requestTemplates": {
        "application/json": "\"statusCode\": 200"
      },
      "responses": {
        "default": {
          "statusCode": "200",
          "responseParameters": {
            "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,Cache-Control'",
            "method.response.header.Access-Control-Allow-Methods": "'*'",
            "method.response.header.Access-Control-Allow-Origin": "'*'"
          },
          "responseModels": {},
          "responseTemplates": {
            "application/json": ""
          }
        }
      }
    }
  ],
  "events": [],
  "environment": {
    "SERVERLESS_PROJECT": "${project}",
    "SERVERLESS_STAGE": "${stage}",
    "SERVERLESS_REGION": "${region}",
    "MYVARIABLES": "${truncated-my-variables}"
  },
  "vpc": {
    "securityGroupIds": [],
    "subnetIds": []
  }
}
```


[directory structure.txt](https://github.com/serverless/serverless/files/195547/directory.structure.txt)

**Comment by eahefnawy** [comment]
hmmmm I see that you only have a single `package.json` file and `node_modules` folder, which are in the root directory of the project. If you want to deploy that `node_modules` folder with your `sendRequest` function, the handler should look like this: `"handler" : "sendRequest/handler.handler"` 

If you want to keep the handler as it is, you need to add a new `sendRequest/package.json` with the lambda dependencies, and `npm install` in the `sendRequest` folder. Your dependencies should now be available after deploy.

I hope that makes sense, could you try it?

btw where's `handler.js` in the directory structure above?!

**Comment by nirmalgoswami** [comment]
@eahefnawy i have different case then @vbuser2004  so i am also sharing my folder structure,s-function.json file to you.so you can debug issue.:)
```
Project
  |---_meta
  |------resource
  |------variables
  |---functions
  |------lib
  |------node_modules
  |---------mysql       //have problem with this - throw can not find module on real aws api gateway url
  |------user
  |---------event.json
  |---------handler.js
  |---------s-function.json /// sharing this file above
  |---------s-templates.json
  |---node_modules
  |------serverless-offline
  |------serverless-opmizer-plugin
  |---admin.env
  |---package.json
  |---s-project.json
  |---s-resources-cf.json
```

`s-function.json`

```
{
  "name": "user",
  "runtime": "nodejs",
  "customName": false,
  "customRole": false,
  "handler": "user/handler.handler",
  "timeout": 10,
  "memorySize": 1024,
  "authorizer": {},
  "custom": {
    "excludePatterns": [],
    "envVars": [],
    "optimize": {
      "exclude": [
        "aws-sdk",
        "mysql"
      ]
    },
    "includePaths": [
      "config",
      "node_modules/mysql"
    ]
  },
  "endpoints": [
    {
      "path": "user",
      "method": "GET",
      "type": "AWS",
      "authorizationType": "none",
      "authorizerFunction": false,
      "customAuthorizer": false,
      "apiKeyRequired": true,
      "requestParameters": {},
      "requestTemplates": "$${apiGatewayRequestTemplate}",
      "responses": {
        "400": {
          "statusCode": "400"
        },
        "default": {
          "statusCode": "200",
          "responseParameters": {},
          "responseModels": {},
          "responseTemplates": {
            "application/json": ""
          }
        }
      }
    }
  ],
  "events": [],
  "environment": {
    "SERVERLESS_PROJECT": "projectname",
    "SERVERLESS_STAGE": "${stage}",
    "SERVERLESS_REGION": "${region}"
  },
  "vpc": {
    "securityGroupIds": [""],
    "subnetIds": [""]
  }

}
```

**Note** also tried the `-t` flag after `sls function deploy` and i can found `node_modules` folder in `tmp` dir,but problem arrive on aws api gateway url...it was work fine with serverless `0.4.2` but have issue with `0.5.1`

**Comment by nirmalgoswami** [comment]
@andersdn i can not understand your point.can you please check my folder structure and explain again ?

**Comment by eahefnawy** [comment]
so you found the `node_modules` folder in `tmp` but not `mysql` inside of it?

**Comment by nirmalgoswami** [comment]
also found `mysql` folder in `node_modules` but have issue on real aws api gateway,in local it is working fine by using offline plugin

**Comment by nirmalgoswami** [comment]
i am using optimizer plugin too,may be have issue with it,dont know

**Comment by eahefnawy** [comment]
hmmmm if you see `tmp/node_modules/mysql`, then it's deployed to AWS. Maybe it's something on their side?

**Comment by nirmalgoswami** [comment]
@eahefnawy need to check,will check and let you know,as per your understanding is this serverless bug or optimizer bug or aws bug or my bug :)

**Comment by nirmalgoswami** [comment]
@eahefnawy issue is related optimizer plugin not serverless i have checked that
`without optimizer plugin it is working fine`

**Comment by nirmalgoswami** [comment]
closing this issue because this is not related `serverless` . issue is related to the `serverless-optimizer-plugin`

**Comment by chrismcleod** [comment]
I'm having this problem but not using the optimizer plugin
