### ISSUE TITLE
Serverless Deploy Re-including files does not work after a Global Exclude

### ISSUE THREAD

**Issue by Atahanak** [serverless/serverless#5329]
# This is a (Bug Report / Feature Proposal)
BUG REPORT

## Description

***
I excluded my src and node_modules directory by a global exclude as follows:

package:
individually: true
exclude:
- node_modules/**
- src/**

and then re-include the related files for each function as follows:

functions:
addItem:
handler: src/addItem.handler
name: ${self:provider.stage}-addItem
package:
include:
- src/addItem.js
- node_modules/request
- node_modules/cheerio

however i got the error:

Serverless Error ---------------------------------------

No file matches include / exclude patterns

which is contradicting with the information provided at https://serverless.com/framework/docs/providers/aws/guide/packaging/
***

For bug reports:
* What went wrong?
None of my files were deployed to aws. 
* What did you expect should have happened?
I expected that the files that i re-included would be deployed to the aws.
* What was the config you used?
-
* What stacktrace or error message from your provider did you see?
Serverless Error ---------------------------------------
 
  No file matches include / exclude patterns
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.11.2
     Serverless Version:     1.27.3

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

## Additional Data

* ***Serverless Framework Version : 1.27.3***:
* ***macOS High Sierra 10.13.5***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by tryantwit** [comment]
Running into this same issue. Seems to be related to nested handlers. If you exclude at the same level as the serverless.yml file and re-include at the same level it works fine.

I would expect given the serverless documentation and a project structure like below:

serverless.yml
func1
|- handler.js
func2
|- handler.js

That you could globally exclude files and directories then for each individual function pull in just what you require. Instead in the serverless.yml I have to do:

```js
package:
  individually: true

func1:
  handler: func1/handler.js
  package:
     exclude:
        - "**/**"
     include:
        - func1/handler.js
        - func1/node_modules
func2:
  handler: func2/handler.js
  package:
     exclude:
        - "**/**"
     include:
        - func2/handler.js
        - func2/node_modules
```

instead of

```js
package:
  individually: true
  exlcude:
     - "**/**"
func1:
  handler: func1/handler.js
  package:
    include:
       - func1/handler.js
       - func1/node_modules
func2:
  handler: func2/handler.js
  package:
    include:
      - func2/handler.js
      - func2/node_modules
```

Using SLS_DEBUG=* yields if that helps:

  Stack Trace --------------------------------------------
 
ServerlessError: No file matches include / exclude patterns
    at globby.then.filePaths (/Users/tim.ryan/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:158:13)
    at <anonymous>
From previous event:
    at Package.resolveFilePathsFunction (/Users/tim.ryan/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:129:48)
    at Package.packageFunction (/Users/tim.ryan/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:105:17)
    at _.map.functionName (/Users/tim.ryan/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:54:21)
    at arrayMap (/Users/tim.ryan/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/node_modules/lodash/lodash.js:639:23)
    at Function.map (/Users/tim.ryan/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/node_modules/lodash/lodash.js:9556:14)
    at Package.packageService (/Users/tim.ryan/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/plugins/package/lib/packageService.js:42:31)
From previous event:
    at Object.package:createDeploymentArtifacts [as hook] (/Users/tim.ryan/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/plugins/package/package.js:67:10)
    at BbPromise.reduce (/Users/tim.ryan/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/Users/tim.ryan/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.spawn (/Users/tim.ryan/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/classes/PluginManager.js:408:17)
    at Deploy.BbPromise.bind.then.then (/Users/tim.ryan/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:123:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/Users/tim.ryan/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:113:10)
    at BbPromise.reduce (/Users/tim.ryan/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/Users/tim.ryan/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.run (/Users/tim.ryan/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/classes/PluginManager.js:421:17)
    at variables.populateService.then.then (/Users/tim.ryan/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Serverless.run (/Users/tim.ryan/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/Users/tim.ryan/.nvm/versions/node/v8.11.2/lib/node_modules/serverless/bin/serverless:43:50)
    at <anonymous>

**Comment by dschep** [comment]
reproduced in [dschep/sls-5329](https://github.com/dschep/sls-5329)

**Comment by johndoe2361289638165** [comment]
Any update on this?

**Comment by ishanjain28** [comment]
I have been hit with the same bug. My serverless config looks like the one someone else posted in this thread.

```
package:
  individually: true

func1:
  handler: func1/handler.js
  package:
     exclude:
        - "**/**"
     include:
        - func1/handler.js
        - func1/node_modules
func2:
  handler: func2/handler.js
  package:
     exclude:
        - "**/**"
     include:
        - func2/handler.js
        - func2/node_modules
```

**Comment by johndww** [comment]
Any update on this? I also get hit with this when using the "!" exclude/reinclude syntax referenced in https://serverless.com/framework/docs/providers/aws/guide/packaging/ :
```
package:
  exclude:
    - ./**
    - '!../bin/**'

function:
  testfn:
    individually: true
    exclude:
      - '../bin/**'
    include:
      - ./testbinary
```

This is working correctly in 1.34.1 . I bisected all changes from the file that throws the error (`serverless/lib/plugins/package/lib/packageService.js:209`) and I believe the commit:
https://github.com/serverless/serverless/commit/23c37b7543238e4a98ab605c2cf8146a3095bcce#diff-0333f308ebf44d187c45d0955bfe24c1 / https://github.com/serverless/serverless/pull/5574
is what broke this functionality. (it works in 1.34.1 but not in 1.35.0 and that was the only commit in that file between the two versions)

+ @dschep

**Comment by mrchief** [comment]
Wildcard exclusion seems buggy.

```
package:
  exclude:
    - '**/**' . // also tried ./** with same results
  include:
    - src/**/!__*/**/*.js
    - package*.json
    - index.js
```

results in 

```
 - package-lock.json
 - package.json
 - index.js
```

Nothing from `src` gets included.

**Comment by mrchief** [comment]
It seems like it uses [nanomatch](https://github.com/micromatch/nanomatch#features) but then negation works - so there's some custom logic involved. It'd help a lot if this info is mentioned in the docs. `globs` is a very broad term.

**Comment by tcastelli** [comment]
Found same error, can confirm the workaround does the trick

**Comment by robertsamarji** [comment]
Has there been any update on this? The workaround is fine, but it'd be better to have the fix in accordance with the documentation.

The serverless YAML below does not package "database/invokeDatabaseLambda.js" and instead returns an error message "Cannot find module '../database/invokeDatabaseLambda.js'".

```
package:
  individually: true
  exclude:
   - database/**

functions:
  report:
    handler: report/report.report
    package:
      include:
        - database/invokeDatabaseLambda.js
```

**Comment by KingDarBoja** [comment]
Got same issue, the excluding syntax `".*/**"` doesn't work, neither `"**/**"` on the global exclude, as trying to re-include will trigger the same error as the author describes.

**Comment by PSP-Developers** [comment]
Probably one the reason can be specified will be wrong.

Please check structure
- serverless.yml
- db/

```
layers:
  layerA:
    path: db  (path should be correct layer path)
    name: layerA
    description: All mongo models and DB connections
    compatibleRuntimes: # optional, a list of runtimes this layer is compatible with
      - nodejs12.x
```

**Comment by Astenna** [comment]
Hint in case somebody is stuck on _No file matches include / exclude patterns_ error like me:

I'm using: (sls --version output)
Framework Core: 3.30.1 (standalone)
Plugin: 6.2.3
SDK: 4.3.2

The global exclude (i.e. "**/**")+ include on specific files works correctly (for example "bin/file"). However, as the error message does not indicate for which function there are no matching files, I thought it's a problem related to all my functions (esp given what I read in this github issue). I lost an hour playing with different includes/excludes specs, whereas it was the built of my one of my functions' handlers that failed. My suggestion would be to **indicate in the error message** which function's files are missing.

Besides, given that global exclude (i.e. "**/**") and then include (directory/file) work correctly, isn't the problem fixed now? shouldn't this github issue be closed?
