### ISSUE TITLE
serverless preuninstall Error: Cannot find module 'shelljs/global'

### ISSUE THREAD

**Issue by jongear** [serverless/serverless#3383]
# This is a Bug Report

## Description

Receiving error when upgrading from 1.8.0 to 1.9.0
```
 Error: Cannot find module 'shelljs/global'
```
Similar or dependent issues:
* #3251 
* #3079

<img width="940" alt="screen shot 2017-03-17 at 9 32 57 pm" src="https://cloud.githubusercontent.com/assets/8430731/24068300/57985ed2-0b59-11e7-85ca-e14bf1631c92.png">

**Comment by pmuens** [comment]
Thanks for reporting @jongear 👍 !

Closing this because w're tracking progress in #3251
