### ISSUE TITLE
Function excludePatterns cannot be templatized

### ISSUE THREAD

**Issue by joshwils82** [serverless/serverless#1135]
It appears that templates cannot be used for excludePatterns.  I have the following in my s-function.json

```
  "custom": {
    "excludePatterns": "$${defaultExcludes}"
  }
```

And in my s-templates.json

```
"defaultExcludes": [ "test" ]
```

However, I receive an error when attempting to deploy the function:

```
sls function deploy -s josh -r us-east-1 -t
Serverless: Deploying the specified functions in "josh" to the following regions: us-east-1  
/home/jwilson/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/lib/Runtime.js:143
        return !excludePatterns.some(sRegex => {
                                ^

TypeError: excludePatterns.some is not a function
  at /home/jwilson/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/lib/Runtime.js:143:33
  at startCopy (/home/jwilson/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/node_modules/fs-extra/lib/copy/ncp.js:42:14)
  at ncp (/home/jwilson/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/node_modules/fs-extra/lib/copy/ncp.js:32:3)
  at /home/jwilson/.nvm/versions/node/v4.3.2/lib/node_modules/serverless/node_modules/fs-extra/lib/copy/copy.js:35:29
  at FSReqWrap.cb [as oncomplete] (fs.js:212:19)
```

From the debugging I have done, it appears that the templated value is not being resolved and that is causing the error.

Serverless version: 0.5.5
Platform: ubuntu 14.04

**Comment by Govinda-Fichtner** [comment]
I am getting the exact same error:

```
Serverless: Loading... /usr/local/lib/node_modules/serverless/lib/Runtime.js:143
        return !excludePatterns.some(sRegex => {
                                ^

TypeError: excludePatterns.some is not a function
    at /usr/local/lib/node_modules/serverless/lib/Runtime.js:143:33
    at startCopy (/usr/local/lib/node_modules/serverless/node_modules/fs-extra/lib/copy/ncp.js:42:14)
    at ncp (/usr/local/lib/node_modules/serverless/node_modules/fs-extra/lib/copy/ncp.js:32:3)
    at /usr/local/lib/node_modules/serverless/node_modules/fs-extra/lib/copy/copy.js:35:29
    at FSReqWrap.cb [as oncomplete] (fs.js:212:19)
```

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.
