### ISSUE TITLE
"map is not a function" error with Serverless release 1.73.0

### ISSUE THREAD

**Issue by grahamdaw** [serverless/serverless#7844]
The following error occurs with Serverless 1.73.0

```
[Container] 2020/06/16 13:26:18 Running command serverless deploy --stage ${STAGE}
Serverless: Packaging service...
Serverless: Excluding development dependencies...

  Type Error ---------------------------------------------

  TypeError: (this.serverless.service.provider.usagePlan || []).map is not a function
      at /usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js:54:64
      at Array.forEach (<anonymous>)
      at AwsCompileApigEvents.compileApiKeys (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js:48:48)
```

It looks like this area was changed in 1.73.0 when moving away from Lodash:
https://github.com/serverless/serverless/commit/4c6f8be5ccae88034e19f72a53996208dd4a56d5

This previously was working with Serverless 1.72.0.

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: api
provider:
  name: aws
  runtime: nodejs12.x 
  region: ${file(./serverless/config.yml):${self:provider.stage}.awsRegion}
  stage: ${opt:stage, 'v1'}
  apiKeys:
    - name: ${self:provider.stage}-web
      description: Api key for web apps
  usagePlan: 
    quota:
      limit: 10000000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 100
      rateLimit: 10
functions:
```

</details>

<details>
<summary><b><code>serverless deploy --stage v1</code> output</b></summary>

```
| 1592313978824 | [Container] 2020/06/16 13:26:18 Running command serverless deploy --force --stage ${STAGE}                                                                                                    |
| 1592313980861 | Serverless: Packaging service...                                                                                                                                                              |
| 1592313980861 | Serverless: Excluding development dependencies...                                                                                                                                             |
| 1592313995736 |                                                                                                                                                                                               |
| 1592313995736 |   Type Error ---------------------------------------------                                                                                                                                    |
| 1592313995736 |                                                                                                                                                                                               |
| 1592313995736 |   TypeError: (this.serverless.service.provider.usagePlan || []).map is not a function                                                                                                         |
| 1592313995736 |       at /usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js:54:64                                                                        |
| 1592313995736 |       at Array.forEach (<anonymous>)                                                                                                                                                          |
| 1592313995736 |       at AwsCompileApigEvents.compileApiKeys (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js:48:48)                                  |
| 1592313995736 |       at AwsCompileApigEvents.tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)                                                              |
| 1592313995736 |       at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)                                                        |
| 1592313995736 |       at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)                                                                   |
| 1592313995736 |       at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)                                                                  |
| 1592313995736 |       at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)                                                                  |
| 1592313995736 |       at _drainQueueStep (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:93:12)                                                                             |
| 1592313995736 |       at _drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)                                                                                  |
| 1592313995736 |       at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)                                                                          |
| 1592313995736 |       at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)                                               |
| 1592313995736 |       at processImmediate (internal/timers.js:456:21)                                                                                                                                         |
| 1592313995736 |       at process.topLevelDomainCallback (domain.js:137:15)                                                                                                                                    |
| 1592313995736 |                                                                                                                                                                                               |
| 1592313995736 |      For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.                                                                                                      |
| 1592313995736 |                                                                                                                                                                                               |
| 1592313995736 |   Get Support --------------------------------------------                                                                                                                                    |
| 1592313995736 |      Docs:          docs.serverless.com                                                                                                                                                       |
| 1592313995736 |      Bugs:          github.com/serverless/serverless/issues                                                                                                                                   |
| 1592313995736 |      Issues:        forum.serverless.com                                                                                                                                                      |
| 1592313995736 |                                                                                                                                                                                               |
| 1592313995736 |   Your Environment Information ---------------------------                                                                                                                                    |
| 1592313995736 |      Operating System:          linux                                                                                                                                                         |
| 1592313995736 |      Node Version:              12.16.3                                                                                                                                                       |
| 1592313995736 |      Framework Version:         1.73.0                                                                                                                                                        |
| 1592313995736 |      Plugin Version:            3.6.13                                                                                                                                                        |
| 1592313995736 |      SDK Version:               2.3.1                                                                                                                                                         |
| 1592313995736 |      Components Version:        2.30.15                                                                                                                                                       |

```

</details>

<b>Installed version</b>

```
Framework Core: 1.73.0
Plugin: 3.6.13
SDK: 2.3.1
Components: 2.30.15 
```

**Comment by medikoo** [comment]
@grahamdaw great thanks for reporting. Fix will be published shortly
