### PR TITLE
feat(AWS ALB): Make it possible to specify the TargetGroup name

### PR DESCRIPTION
**Pull request by cbm-gplassard**
Corresponding issue : https://github.com/serverless/serverless/issues/9213

@pgrzesik I'm not sure about the `getAlbTargetGroupNameTagValue` function. For example today it doesn't uses the `provider.alb.targetPrefix` property and creates a name which is more aligned with other generated names by serverless. Also it doesn't require to be less than 32 characters, nor to be unique. So I guess it's a good place to have a more precise name with less constraints. What do you think ?

I didn't modify it but if you want me to change it and juste return  `provider.alb.targetPrefix + targetGroupName` when it's defined I will.

I'm having issues with the master branch of serverless (`pathType.dirSync is not a function` ? it still works with 2.32.1. Or maybe it's not supposed to work using npm link ?) so I couldn't deploy it, but when using the `package` command I have the expected cloudformation template.

Closes: 9213

### CODE REVIEW

File: lib/plugins/aws/lib/naming.js [hunk 1]
```diff
@@ -448,7 +448,11 @@ module.exports = {
       multiValueHeaders ? 'multi-value-' : ''
     }${this.provider.getStage()}`;
   },
-  getAlbTargetGroupName(functionName, albId, multiValueHeaders) {
+  getAlbTargetGroupName(targetGroupName, functionName, albId, multiValueHeaders) {
+    if (targetGroupName) {
+      return this.provider.getAlbTargetGroupPrefix() + targetGroupName;
```
Comment (medikoo) [inline lib/plugins/aws/lib/naming.js:453]: I believe that in that case we should not rely on `provider.alb.targetGroupPrefix` at all.

This property was introduced to have some constant prefix in names which represent md5 hashes, as with md5 hashes, even small change in string we hash, results in completely different hash (so e.g. `foo-dev` and `foo-prod` will result with completely different names, so even though service name didn't change, we receive no common prefix for both names).

Now, when we explicitly set the name, there's no longer this problem, and I believe there's no use case here to rely on `provider.alb.targetGroupPrefix`  (we just probably should add in documentation that this setting is exclusive to `functions[].events[].alb.targetGroupName`)

Ideally we should also throw if both are used.

File: lib/plugins/aws/package/compile/events/alb/index.js [hunk 2]
```diff
@@ -101,6 +101,7 @@ class AwsCompileAlbEvents {
         },
         multiValueHeaders: { type: 'boolean' },
         priority: { type: 'integer', minimum: 1, maximum: 50000 },
+        targetGroupName: { type: 'string', minLength: 1, maxLength: 32 },
```
Comment (medikoo) [inline lib/plugins/aws/package/compile/events/alb/index.js:104]: Does AWS has any specific naming rules to this name? Are all chars allowed? If we know the allowed charset it might be nice to set `pattern` property

File: lib/plugins/aws/package/compile/events/alb/lib/targetGroups.js [hunk 3]
```diff
@@ -62,7 +68,12 @@ module.exports = {
               Id: resolveLambdaTarget(functionName, functionObj),
             },
           ],
-          Name: this.provider.naming.getAlbTargetGroupName(functionName, albId, multiValueHeaders),
+          Name: this.provider.naming.getAlbTargetGroupName(
```
Comment (medikoo) [inline lib/plugins/aws/package/compile/events/alb/lib/targetGroups.js:71]: Technically it could be: `targetGroupName || this.provider.naming.getAlbTargetGroupName(..)`.

**Review by medikoo — CHANGES_REQUESTED** [review]
@cbm-egoubely great thanks for that! Please see my comments.

Additionally it'll be good to add some test that confirms that new property works as expected

File: lib/plugins/aws/lib/naming.js (hunk 1 above)
Comment (cbm-gplassard) [reply lib/plugins/aws/lib/naming.js:453]: Indeed I wasn't sure which was the best behavior, I will change as you suggest !

File: lib/plugins/aws/package/compile/events/alb/index.js (hunk 2 above)
Comment (cbm-gplassard) [reply lib/plugins/aws/package/compile/events/alb/index.js:104]: Indeed you're right, it should only contain hyphens and alphanumeric, I will add a pattern : https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html#cfn-elasticloadbalancingv2-targetgroup-name

File: lib/plugins/aws/package/compile/events/alb/lib/targetGroups.js (hunk 3 above)
Comment (cbm-gplassard) [reply lib/plugins/aws/package/compile/events/alb/lib/targetGroups.js:71]: Indeed it felt a bit strange to pass it as a parameter but with the naming used I thought it would be better to handle the naming in only one place. What do you think ?

Maybe should I rename it to something like `generateAlbTargetGroupName` ? As you prefer

Comment (medikoo) [reply lib/plugins/aws/package/compile/events/alb/lib/targetGroups.js:71]: > Maybe should I rename it to something like generateAlbTargetGroupName ? As you prefer

I had exactly same thought. We're a bit cautious with renames as it may happen that some external plugin may attach to that (even though this area is considered private), but in this case it's unlikely, so I think we can rename

**Comment by cbm-gplassard** [comment]
@cbm-egoubely was the original contributor of this feature but he is not making this one ^^

What kind of tests are you referring to ? I'm gonna make more manual testing on my end once I find why I have the `pathType.dirSync is not a function` error. But are there other places in which I could add automated tests ?

**Comment by medikoo** [comment]
> What kind of tests are you referring to ?

Add ``should support `functions[].events[].alb.targetGroupName` property`` test to this file: https://github.com/serverless/serverless/blob/9d84596604a7338e82616723fe1a486c09272ae7/test/unit/lib/plugins/aws/package/compile/events/alb/index.test.js

**Comment by cbm-gplassard** [comment]
Hello @medikoo, I think I adressed your comments, is it okay for you ? Thanks ! (sorry I had some issues making the tests work on my machine which made me make multiple commits that I ammended)

File: lib/plugins/aws/package/compile/events/alb/lib/validate.js [hunk 4]
```diff
@@ -63,6 +63,12 @@ module.exports = {
             if (event.alb.multiValueHeaders) {
               albObj.multiValueHeaders = event.alb.multiValueHeaders;
             }
+            if (event.alb.targetGroupName) {
+              albObj.targetGroupName = this.validateTargetGroupName(
```
Comment (medikoo) [inline lib/plugins/aws/package/compile/events/alb/lib/validate.js:67]: Let's not create `validateTargetGroupName` method, but simply validate it inline. If I see correctly there's no re-use use case here.

File: test/unit/lib/plugins/aws/package/compile/events/alb/lib/validate.test.js [hunk 5]
```diff
@@ -258,4 +258,20 @@ describe('#validate()', () => {
       );
     });
   });
+
+  describe('#validateTargetGroupName()', () => {
```
Comment (medikoo) [inline test/unit/lib/plugins/aws/package/compile/events/alb/lib/validate.test.js:262]: Let's remove this tests (all tests should be configured via `runServerless` util -> https://github.com/serverless/serverless/tree/master/test#unit-tests

Also I'd keep all tests in `index.test.js` (this file is leftover of legacy tests, which we didn't refactor yet).

Summarizing, we can add another test in `index.test.js` but which has its own `runServerless` run configured. Then we should test the result error code. as e.g. it's done here: https://github.com/serverless/serverless/blob/0e6a1ce2d4a28a480683192cc6ac639c7bfe0d8b/test/unit/lib/plugins/aws/package/compile/events/httpApi.test.js#L541-L573

**Review by medikoo — CHANGES_REQUESTED** [review]
Thank you @cbm-gplassard It looks very good! I've just suggested an improvement to validation test (so it's up to currently practiced conventions), let me know if anything is not clear.

File: test/unit/lib/plugins/aws/package/compile/events/alb/lib/validate.test.js (hunk 5 above)
Comment (cbm-gplassard) [reply test/unit/lib/plugins/aws/package/compile/events/alb/lib/validate.test.js]: I tested both cases, with a `targetGroupPrefix` to check that it's rejected and the nominal case with the Name property being correctly set

File: test/unit/lib/plugins/aws/package/compile/events/alb/index.test.js [hunk 6]
```diff
@@ -219,4 +217,75 @@ describe('lib/plugins/aws/package/compile/eents/alb/index.test.js', () => {
...
+      expect(result.cfTemplate.Resources[albListenerRuleLogicalId].Properties.Name).to.equal(
+        'custom-targetgroup-name'
+      );
+    });
+
+    it('should reject if `provider.alb.targetGroupPrefix` is also specified', async () => {
+      const runServerlessAction = () =>
+        runServerless({
+          fixture: 'function',
+          cliArgs: ['package'],
```
Comment (medikoo) [inline test/unit/lib/plugins/aws/package/compile/events/alb/index.test.js:259]: Rebase against master and put `command: 'package'` instead (we've just upgraded to new version of `runServerless` -> https://github.com/serverless/serverless/pull/9281)

File: test/unit/lib/plugins/aws/package/compile/events/alb/index.test.js [hunk 7]
```diff
@@ -219,4 +217,75 @@ describe('lib/plugins/aws/package/compile/eents/alb/index.test.js', () => {
...
+                ],
+              },
+            },
+          },
+        });
+
+      await expect(runServerlessAction())
+        .to.eventually.be.rejectedWith(ServerlessError)
+        .and.have.property(
+          'message',
```
Comment (medikoo) [inline test/unit/lib/plugins/aws/package/compile/events/alb/index.test.js:286]: Let's test against `code` (`message` is subject to grammar improvements, while `code` is meant to never change)

**Review by medikoo — CHANGES_REQUESTED** [review]
Thank you @cbm-gplassard ! Looks great, I've proposed just one last improvement to tests and we should be good

File: test/unit/lib/plugins/aws/package/compile/events/alb/index.test.js [hunk 8]
```diff
@@ -219,4 +217,72 @@ describe('test/unit/lib/plugins/aws/package/compile/events/alb/index.test.js', (
...
+          functions: {
+            fnTargetGroupName: {
+              handler: 'index.handler',
+              events: [
+                {
+                  alb: {
+                    ...validBaseEventConfig,
+                    priority: 1,
+                    targetGroupName: 'custom-targetgroup-name',
+                  },
```
Comment (medikoo) [inline test/unit/lib/plugins/aws/package/compile/events/alb/index.test.js:236]: As `runServerless` runs are expensive, it'll be great to reuse one setup here: https://github.com/serverless/serverless/blob/3b1225a28abb08ac4d9d098e2f1606cf8b7c77b6/test/unit/lib/plugins/aws/package/compile/events/alb/index.test.js#L36.

Ideally we shoudl add there another function with `events[].alb.targetGroupName` and add:

```javascript
describe("general support", () => {
  it('should support `functions[].events[].alb.targetGroupName` property', () => {
    ...
  });
});
```

(it doesn't apply to second test, where we confirm on rejection, as those can only be tested with individual runServerless runs)

**Review by medikoo — CHANGES_REQUESTED** [review]
@cbm-egoubely great thanks for update!

Sorry, I've just noticed one last thing that it'll be good to improve in tests. To have sensible testing performance we do our best to minimize count of `runServerless` runs, and usually test support for many properties with single run

Here I've just noticed that new `runServerless` run is configured, why without issues we can reuse one above

File: test/unit/lib/plugins/aws/package/compile/events/alb/index.test.js (hunk 8 above)
Comment (cbm-gplassard) [reply test/unit/lib/plugins/aws/package/compile/events/alb/index.test.js]: Hello, @medikoo I'm not 100% sure how you want to organize the tests, there is no "general support section" currently.

So i kept my 2 tests in

* ```should support `functions[].events[].alb.targetGroupName` property```
  * ```should use it if defined```
  * ```should reject if `provider.alb.targetGroupPrefix` is also specified```

Do you wanted another organization ?

**Review by medikoo — APPROVED** [review]
@cbm-egoubely thank you! It's great that way

**Comment by cbm-egoubely** [comment]
@medikoo I think you meant @cbm-gplassard ;) (must be the autocompletion..)

**Comment by medikoo** [comment]
> @medikoo I think you meant @cbm-gplassard ;) (must be the autocompletion..)

@cbm-egoubely sorry, this github autocompletion just doesn't work as expected :)

@cbm-gplassard great work, thank you!

**Comment by cbm-gplassard** [comment]
No problem ! ^^
Thanks for the review and the merge !
