### ISSUE TITLE
After upgrade to 1.33.1 Getting error on local invoke

### ISSUE THREAD

**Issue by filanthropic** [serverless/serverless#5499]
Upgraded to 1.33.1. 

When I issue this command: `serverless invoke local -f Function_Name -p event.json`

Getting this error:

```
starting...

Traceback (most recent call last):
  File "/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/invoke.py", line 77, in <module>

    tty = subprocess.run('tty', stdout=subprocess.PIPE, stderr=subprocess.PIPE)
AttributeError: 'module' object has no attribute 'run'
```

Using python 2.7

**Comment by dschep** [comment]
Thanks for the bug report @filanthropic seems the fact `subprocess.run` was only added in python3 was overlooked when that code was added. I'll make a PR to fix it shortly.

**Comment by dschep** [comment]
Fix released in v1.33.2
