### PR TITLE
Fix node_modules (serverless plugins) lookup

### LINKED ISSUE #2619: Allow plugins to be loaded from parent node_modules folder
# This is a Feature Proposal

## Description

V.1 conflates dev dependencies and regular dependencies but gives you no easy way to exclude the dev dependencies, causing Lambdas to be larger than necessary.  

V.0 resolved this issue by having dev dependencies installed in the parent folder (formerly known as the project folder).  

By allowing plugins to be loaded from a parent `node_modules` folder, not just the current service folder, we can easily solve this issue since the service folder is the deployment unit.

### PR DESCRIPTION
**Pull request by nrako**
## What did you implement:

Closes #2619

Fix to allow plugins to be installed in parent directory. i.e for when you have some transpiling/bundling mechanism that doesn't require to package and deploy the whole `node_modules` directory nor maintain a big list of `excludes`/`includes` in the config.

## How did you implement it:

This reset the `module.paths` relatively to the current working directory
`process.cwd()`. So the array of paths used to resolve packages is relative
to where the `serverless` CLI is run.

```node
const Module = require('module')
module.paths = Module._nodeModulePaths(process.cwd())

// /path_to_service/.serverless-plugins path is still added
```

Similar to i.e `babel-cli` https://github.com/babel/babel/blob/396634a51df1941b3a46f81fbee5904ceb72471a/packages/babel-cli/src/_babel-node.js#L84-L88

## How can we verify it:

```shell
$ mkdir testit && cd testit
$ npm i serverless-webpack
$ mkdir service && cd service
$ serverless create --template aws-nodejs
$ cat <<EOT>> serverless.yml
plugins:
  - serverless-webpack
EOT
$ serverless | grep "Cannot find module" > /dev/null && echo "NOT OK 👎"
$ npm uninstall -g serverless
$ npm i -g nrako/serverless#4c3673a
$ serverless | grep "Cannot find module" > /dev/null || echo "OK 👍"
```

## Todos:

- [x] Write tests???
- ~~[ ] Write documentation~~
- [x] Fix linting errors
- [x] Make sure code coverage hasn't dropped
- [x] Provide verification config / commands / resources
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by pmuens** [comment]
Thanks for the PR @nrako 💯 

Referencing https://github.com/serverless/serverless/issues/2895 here since it might help there!

File: lib/classes/PluginManager.js [hunk 1]
```diff
@@ -75,20 +76,15 @@ class PluginManager {
...
-        path.join(this.serverless.config.servicePath, '.serverless_plugins')
-        );
+      module.paths.unshift(path.join(this.serverless.config.servicePath, '.serverless_plugins'));
     }
 
     this.loadPlugins(servicePlugins);
-
-    // restore module paths
-    if (this.serverless && this.serverless.config && this.serverless.config.servicePath) {
-      module.paths.shift();
```
Comment (pmuens) [inline lib/classes/PluginManager.js]: Why is this restoring not needed anymore (since were still shifting with `.serverless_plugins`)?

Comment (nrako) [inline lib/classes/PluginManager.js]: My understanding is that `serverless` is only meant to be used as a CLI so it should be fine if the `module.paths` is replaced during it's runtime and not restored. Or am I missing something?

**Comment by nrako** [comment]
@pmuens thanks for your review, I'll add some test in the next days.

**Comment by pmuens** [comment]
Hey @nrako thanks! 👍 

Let us know if you need any help...

**Comment by nrako** [comment]
Hey @pmuens, I've been looking into adding some test for this and I'm stuck. `mock-require` doesn't allow to mock this kind of scenario (`mockRequire('../node_modules/plugin', Plugin)`,and trying to assert that the `PluginManager`'s `module.paths` has some expected values is not simple either 😓 

If someone would know a simple approach to test this I'd gladly accept any help.

File: lib/classes/PluginManager.js (hunk 1 above)
Comment (pmuens) [inline lib/classes/PluginManager.js]: Yes, Serverless is meant to be used as a CLI tool. However it might be a good idea to restore the module paths so that it get's into a clean state again.

**Comment by pmuens** [comment]
Hey @nrako thanks for you update about the tests.

What if we create an example service in a temp directory with the following structure:

```
tmp
  |__ my-module
      |__ package.json
      |__ ...
  |__ service
      |__ serverless.yml
      |__ ...
```

And then test if `my-module` is loaded when we run a Serverless command in the `tmp` directory (outside the service).

Might be a little bit more complex / not super pretty but should do the trick... What do you think?

**Comment by nrako** [comment]
Hey @pmuens, actually I didn't paid attention at all to the integrations 🙈.

Adding some integration test in `general/custom-plugins` looks like the way to go for me, WDYT? Or would you rather stick with the collocated `PluginManager.test.js` since you mentioned a `tmp/` directory?

It looks like `custom-plugins` already have all the parts, I would add an another dummy plugin (e.g `serverless-plugin-saluter`) under `custom-plugins/` and assert it can be used  (e.g [general/custom-plugins/tests.js#L29](https://github.com/serverless/serverless/blob/master/tests/integration/general/custom-plugins/tests.js#L29)).
```
├── custom-plugins
│   ├── serverless-plugin-saluter (npm link ... && npm i ...)
│   ├── service
│   │   ├── handler.js
│   │   ├── package.json
│   │   ├── serverless-plugin-greeter
│   │   │   ├── main.js
│   │   │   └── package.json
│   │   └── serverless.yml
│   └── tests.js
```

File: lib/classes/PluginManager.js (hunk 1 above)
Comment (nrako) [inline lib/classes/PluginManager.js]: My understanding is that `module.paths` only have influence for loading within that same module. And therefore my assumption is that restoring the module paths would only be useful if `require()` was used after the paths has been altered, e.g to load a module which would be in the serverless install dir node_modules (or parents) and not in the `process.cwd`. Also I wouldn't know how to test that it's been restored.

Moreover, since all the PluginManger deps are required before it is instantiated and the core plugins are loaded with absolute paths, I think it would be more explicit and future proof to move the `module.paths` reassignment in the `PluginManager.constructor` instead of `loadServicePlugins`. What do you think?

**Comment by pmuens** [comment]
@nrako Yes, good point! 👍 
There's already a kind of "skeleton" test in the `integration` test suite you can re-use!

It would be great if the test for this feature would live in the `PluginManager.test.js` file since the unit tests (including this test) will be run everytime, whereas the integration tests are only triggered when smth. is merged into master.

We've used this type of tests (where a `tmp` directory is used) in other unit tests as well. You can see an example (for the `Service` class) here: https://github.com/serverless/serverless/blob/78092ca194e9b3bac715f4e49c68bebb14d063a9/lib/classes/Service.test.js#L119-L169

Let us know if you need anything else! 👍

**Comment by nrako** [comment]
@pmuens I just added some test. I hope it's going in the right direction. I would gladly address any change request, unfortunately I won't be able to follow-up during the next two weeks so please feel free to take over it.

AFK

File: lib/classes/PluginManager.js (hunk 1 above)
Comment (pmuens) [inline lib/classes/PluginManager.js]: Yes, that's a good point. Thanks for pointing that out! I'll bring it back for now, but we might refactor this so that it's called in the constructor!

Comment (nrako) [inline lib/classes/PluginManager.js]: Hey @pmuens, only doing `modules.paths.shifts()` is not enough anymore to "restore" the original paths, the `paths` should be reset with value prior to `_nodeModulePaths` usage. I still believe that this doesn't do anything but add unnecessary confusion. If I were a maintainer I would remove theses lines or else add a test that can explain why this is needed.

**Comment by nrako** [comment]
Thanks @pmuens! 🙂

I just added a comment related to the `paths` restoration.

AFK

File: lib/classes/PluginManager.js (hunk 1 above)
Comment (pmuens) [inline lib/classes/PluginManager.js]: Alright, sounds reasonable @nrako will do next up 👍

**Comment by nrako** [comment]
@pmuens just passing by, I'm thinking that we could ask @kid why he implemented the paths restore in the first place? In  https://github.com/serverless/serverless/commit/7dd58f032560460a35ae04ef7e562db60b231463#diff-1a6cb15a7aef359bf1fabed7982e4af3R169

Hey @kid can you please help us clear out our questioning here https://github.com/serverless/serverless/pull/3180#discussion_r99952974 thanks 🙏 

AFK

**Comment by pmuens** [comment]
@nrako good idea! 👍

**Comment by nrako** [comment]
Hi @pmuens, I'm back on the ⌨️. I was using this branch and did a force push, sorry about that, I overwrote your commit which was reinstating the `paths` restoration.

I still believe the restoration is unnecessary and add noise. Unfortunately, the original author didn't follow on my mention to help on that.

Any chance of getting this through?

**Comment by pmuens** [comment]
Hey @nrako thanks for following up and thanks for updating the PR 👍 

We're currently planning the upcoming versions and will revisit this PR in this process.

**Comment by nrako** [comment]
Awesome, thank you guys and especially @pmuens for your support!

**Comment by pmuens** [comment]
Thanks for the PR and the kind words @nrako 🎉

**Comment by ProTip** [comment]
Has this broken lookup of global modules? I'm using serverless-wsgi installed globally and after upgrading to 1.9.0 serverless will say ```cannot find module serverless-wsgi``` unless it is installed locally..

**Comment by pmuens** [comment]
🤔 thanks for pointing that out @ProTip 

Seems like it was introduced somewhere else (I reverted all the changes and tested the version of the `PluginManager` before this commit).

Could you open a separate issue for this so that we can track it.

Thanks!

**Comment by nrako** [comment]
@pmuens actually I think @ProTip might be right, this PR might have broken lookup for plugins installed globally.

We might want to use something like https://github.com/jonschlinkert/global-paths to do `module.paths = require('global-paths')();` instead of `module.paths = Module._nodeModulePaths(process.cwd());`.

I'm not a fan of adding a dependency for that but it looks like an acceptable way to make it work on all platform.
The annoying part is in this sub-sub-depedency https://github.com/jonschlinkert/global-prefix/blob/master/index.js

👍 for a separate issue though.

**Comment by pmuens** [comment]
Thanks for looking into it @nrako !

I just created a separate issue to track the loss of the global plugins support (#3409).

/cc @ProTip
