### PR TITLE
Don't use py3.5+ only subprocess.run in python invoke local

### LINKED ISSUE #5499: After upgrade to 1.33.1 Getting error on local invoke
Upgraded to 1.33.1. 

When I issue this command: `serverless invoke local -f Function_Name -p event.json`

Getting this error:

```
starting...

Traceback (most recent call last):
  File "/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/invoke.py", line 77, in <module>

    tty = subprocess.run('tty', stdout=subprocess.PIPE, stderr=subprocess.PIPE)
AttributeError: 'module' object has no attribute 'run'
```

Using python 2.7

### PR DESCRIPTION
**Pull request by dschep**
## What did you implement:

Fixes #5499

invoke local was changed in #5355 to check for a tty by calling the `tty` executable, but it was implemented with `subprocess.run` which was added in Python 3.5 so it doesn't work with Python 2.7 projects

## How did you implement it:

Switched to the older `subprocess.check_call`

## How can we verify it:

```
npm i -g serverless/serverless#fix-py27-invoke-local
sls create -t aws-python
sls invoke local -f hello
```

## Todos:

- [ ] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by dschep** [comment]
@filanthropic mind testing this in the project you ran into #5499? Install as indicated in the PR description ☝️
