### ISSUE TITLE
Broken dependency in commit 93c88c0b8d1eea6455ca6ecb9a022f814f8e79b3

### ISSUE THREAD

**Issue by michalmalinowski1987** [serverless/serverless#9787]
Installed version: 2.52.0

Issue:
When the automatic postinstall script kicks off I get the error:
`error ***/node_modules/serverless: Command failed.
Exit code: 1
Command: node ./scripts/postinstall.js
Arguments: 
Directory: ***/node_modules/serverless
Output:
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'es5-ext/object/for-each'
Require stack:
-***/node_modules/memoizee/plain.js
- ***/node_modules/memoizee/index.js
- ***/node_modules/serverless/lib/utils/npmPackage/isGlobal.js
- ***/node_modules/serverless/scripts/postinstall.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (***/node_modules/memoizee/plain.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '***/node_modules/memoizee/plain.js',
    '***/node_modules/memoizee/index.js',
    '***/node_modules/serverless/lib/utils/npmPackage/isGlobal.js',`

The mentioned object doesn't exist in the `memoizee` repository and it is required by `isNpmGlobalPackage` module introduced in commit 93c88c0b8d1eea6455ca6ecb9a022f814f8e79b3

**Comment by michalmalinowski1987** [comment]
Works fine when I removed serverless 2.52.1 from the package.json and relay on globally installed serverless 2.52.1 but as soon as I add it to the project it breaks.

**Comment by pgrzesik** [comment]
Hello @michalmalinowski1987 - could you please share a bit more about your environment? I've tried to reproduce and I could not manage to - also, the dependency that could not be imported should be there as it's the dependency of the `memoizee`. Was there something that broke your installation by any chance? Do you have `es5-ext` package installed in `node_modules`?

**Comment by michalmalinowski1987** [comment]
Hey, @pgrzesik I had es5-ext installed but inside the "objects" directory I didn't have half of the objects (comparing to the source in GitHub).

Turned out to be a very weird cache issue and after removing `/Caches/Yarn/v6/` everything works well now. I will close with this comment 👍

**Comment by pgrzesik** [comment]
Hey @michalmalinowski1987 :wave: Happy to hear that you were able to sort this out :raised_hands:
