### ISSUE TITLE
After upgrading to version 4.4.5 , get the error - accessKeyV2.trim is not a function

### ISSUE THREAD

**Issue by sohail-norstella** [serverless/serverless#12900]
### Issue description

We have dotnet core 8 application , we use serverless to deploy the application to AWS lambda but when I upgrade serverless to 4.4.5. I got this below error 
![image](https://github.com/user-attachments/assets/f51c23af-6eeb-4cc4-9638-70f5f12f0afb)
 

### Context

Summary Report -----------------

# Service Overview
- Serverless Framework Version: 4.4.5
- Command:  --version true

# Service Overview
- Serverless Framework Version: 4.4.5
- Service Path: D:\NXP-Search\nxp-search-history-service
- Service Config File: serverless.yml
- Service Name: history-service
- Service Runtime: ${param:runtime}
- Service Region: eu-west-1
- Command: deploy

## Error Message
accessKeyV2.trim is not a function

## Error Stacktrace
```
at Authentication.getAuthenticatedData (file:///C:/Users/sohail.khan/.serverless/releases/4.4.5/package/dist/sf-core.js:648:10246)
at async Authentication.resolverAuthenticate (file:///C:/Users/sohail.khan/.serverless/releases/4.4.5/package/dist/sf-core.js:650:20575)
at async _Meta.authenticate (file:///C:/Users/sohail.khan/.serverless/releases/4.4.5/package/dist/sf-core.js:683:31846)
at async _Meta.authenticateAndResolve (file:///C:/Users/sohail.khan/.serverless/releases/4.4.5/package/dist/sf-core.js:683:31518)
at async route (file:///C:/Users/sohail.khan/.serverless/releases/4.4.5/package/dist/sf-core.js:973:13867)
at async Object.run2 [as run] (file:///C:/Users/sohail.khan/.serverless/releases/4.4.5/package/dist/sf-core.js:973:14355)
at async run3 (file:///C:/Users/sohail.khan/.serverless/releases/4.4.5/package/dist/sf-core.js:973:15617)
```

## Service Config
```
service: nxp-search-history-service
frameworkVersion: '4.4.5'
licenseKey: ${ssm:/aws/reference/secretsmanager/Serverless/LICENSE}
params:
  default: ${file(./config/config.yml):${env:ENV, 'dev'}}
provider:
  name: aws
  endpointType: REGIONAL
  runtime: ${param:runtime}
  region: eu-west-1
  apiGateway:
    metrics: true
  deploymentBucket: ${param:deploymentBucket}
  tracing:
    apiGateway: true
    lambda: true
  tags: ${file(./config/tags.yml)}
  stackTags: ${file(./config/tags.yml)}
  iam:
    role:
      name: nxp-${param:application}-${param:environment}-lambda-role
      statements:
      - Effect: Allow
        Action: secretsmanager:ListSecrets
        Resource: "*"
      - Effect: Allow
        Action:
          - secretsmanager:GetSecretValue
          - secretsmanager:DescribeSecret
        Resource: arn:aws:secretsmanager:${param:region}:${param:account}:secret:*
  logs:
    restApi:
      format: >
          '{ "requestId":"$context.requestId",
          "extendedRequestId":"$context.extendedRequestId",
          "sourceIp":"$context.identity.sourceIp",
          "userAgent":"$context.identity.userAgent",
          "requestTime":"$context.requestTime",
          "httpMethod":"$context.httpMethod",
          "resourcePath":"$context.resourcePath",
          "path":"$context.path",
          "cdnBasePathMatched":"$context.customDomain.basePathMatched",
          "status":"$context.status",
          "protocol":"$context.protocol",
          "responseLength":"$context.responseLength",
          "integrationLatency":"$context.integrationLatency",
          "integration-latency":"$context.integration.latency",
          "integrationStatus":"$context.integrationStatus",
          "integration-status":"$context.integration.status",
          "responseLatency":"$context.responseLatency",
          "authorizerError":"$context.authorizer.error",
          "authorizerLatency":"$context.authorizer.latency",
          "authorizerStatus":"$context.authorizer.status",
          "authorizerRequestId":"$context.authorizer.requestId",
          "apiKeyId":"$context.identity.apiKeyId",
          "xrayTraceId":"$context.xrayTraceId",
          "wafLatency":"$context.waf.latency",
          "wafStatus":"$context.waf.status",
          "wafError":"$context.waf.error",
          "userId":"$context.authorizer.principalId"
          }'
  environment:
    environment: dev
custom:
  authorizer: ${param:customLambdaAuthorizerARN}
  prune:
    automatic: true
    includeLayers: true
    number: 5
  customDomains:
    - rest:
        stage: ${param:stage}
        domainName: searchhistoryapi.${param:domainName}
        endpointType: regional
        hostedZoneId: ${param:hostedZoneId}
        certificateDomain: searchhistoryapi.${param:domainName}
        basePath: ''
        createRoute53Record: true
        autoDomain: true
        autoDomainWaitFor: 120
    - rest:
        stage: ${param:stage}
        domainName: search-history-api.${param:domainName}
        endpointType: regional
        hostedZoneId: ${param:hostedZoneId}
        certificateDomain: search-history-api.${param:domainName}
        basePath: ''
        createRoute53Record: true
        autoDomain: true
        autoDomainWaitFor: 120
  associateWaf:
    name: ${param:wafAclName}
    version: V2
package:
  individually: true
functions:
  search-history-lambda:
    name: nxp-${param:application}-${param:environment}-lambda-v4
    handler: NXP.Search.History.Service.Api::NXP.Search.History.Service.Api.LambdaEntryPoint::FunctionHandlerAsync
    memorySize: ${param:lambda_memory}
    environment:
      RDS__CredentialsKey: ${param:rdsCredentialsKey}
    timeout: 15
    package:
      artifact: ${param:packageLocation}
    events:
      - http:
          method: get
          path: "/swagger/{proxy+}"
          integration: lambda-proxy
          cors: true
      - http:
          method: get
          path: "/api/v1/SearchHistory"
          integration: lambda-proxy
          cors: true
          authorizer:
            arn: ${self:custom.authorizer}
            managedExternally: ${param:externalAuthorizer}
      - http:
          method: post
          path: "/api/v1/SearchHistory"
          integration: lambda-proxy
          cors: true
          authorizer:
            arn: ${self:custom.authorizer}
            managedExternally: ${param:externalAuthorizer}
      - http:
          method: any
          path: "/api/v1/SearchHistory/{proxy+}"
          integration: lambda-proxy
          cors: true
          authorizer:
            arn: ${self:custom.authorizer}
            managedExternally: ${param:externalAuthorizer}
      - http:
          method: get
          path: "/api/v1/SearchHistory/ByUser/{email}/{startDate}/{endDate}"
          integration: lambda-proxy
          cors: true
          authorizer:
            arn: ${self:custom.authorizer}
            managedExternally: ${param:externalAuthorizer}
      - http:
          method: get
          path: "/api/v1/SearchHistory/ByNamespace/{namespace}/{startDate}/{endDate}"
          integration: lambda-proxy
          cors: true
          authorizer:
            arn: ${self:custom.authorizer}
            managedExternally: ${param:externalAuthorizer}
      - http:
          method: get
          path: "/api/v1/SearchHistory/ByQueryName/{queryName}/{startDate}/{endDate}"
          integration: lambda-proxy
          cors: true
          authorizer:
            arn: ${self:custom.authorizer}
            managedExternally: ${param:externalAuthorizer}
      - http:
          method: delete
          path: "/api/v1/SearchHistory/BulkDelete"
          integration: lambda-proxy
          cors: true
          authorizer:
            arn: ${self:custom.authorizer}
            managedExternally: ${param:externalAuthorizer}
    vpc:
      securityGroupIds:
        - Ref: LambdaSecurityGroup
      subnetIds:
        "Fn::Split":
          - ","
          - ${param:lambdaSubnetIds}
plugins:
  - serverless-prune-plugin
  - serverless-domain-manager
  - serverless-associate-waf
resources:
  Resources:
    LambdaSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: "Allow all outbound traffic, no inbound for Lambdas"
        SecurityGroupEgress:
          - IpProtocol: "-1"
            FromPort: "0"
            ToPort: "0"
            CidrIp: "0.0.0.0/0"
        VpcId: ${param:VpcId}
        Tags:
          - Key: "Name"
            Value: "${param:productLine}-${param:application}-${param:environment}-sg"
    AuthorizerApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        AuthorizerResultTtlInSeconds: 300
        AuthorizerUri: !Join
        - ''
        - - 'arn:'
          - !Ref 'AWS::Partition'
          - ':apigateway:'
          - ${param:customLambdaAuthorizerRegion}
          - ':lambda:path/2015-03-31/functions/'
          - ${param:customLambdaAuthorizerARN}
          - /invocations
```

**Comment by austencollins** [comment]
Thanks @sohail-norstella We'll look into this right away or provide a workaround

**Comment by czubocha** [comment]
Hey @sohail-norstella. It seems the secret value returned from AWS Secrets Manager is not a string. Could you share how you structured the secret value? To make it work, please ensure that the license key is saved as a plaintext string, not as an key/value object.
<img width="836" alt="image" src="https://github.com/user-attachments/assets/0dffd192-5d27-48ae-9cd9-d1ae4a29d54a">

**Comment by austencollins** [comment]
Closing for now until more information is provided.
