### ISSUE TITLE
After updating to 0.5.5 some commands don't work anymore

### ISSUE THREAD

**Issue by ialmetwally** [serverless/serverless#1254]
I've updated to 0.5.5 and I can no longer deploy or reinitialize the project when I try to execute "sls project init" I get the following error:

```
_______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v0.5.5
`-------'

Serverless: Initializing Serverless Project...
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

TypeError: stage.save is not a function
    at /usr/local/lib/node_modules/serverless/lib/Serializer.js:162:26
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serializer.js:161:28
From previous event:
    at Project.serializeProject (/usr/local/lib/node_modules/serverless/lib/Serializer.js:160:10)
    at Project.serialize (/usr/local/lib/node_modules/serverless/lib/Serializer.js:23:55)
    at Project.save (/usr/local/lib/node_modules/serverless/lib/Project.js:40:19)
    at /usr/local/lib/node_modules/serverless/lib/actions/ProjectInit.js:195:32
From previous event:
    at ProjectInit._scaffold (/usr/local/lib/node_modules/serverless/lib/actions/ProjectInit.js:175:27)
From previous event:
    at ProjectInit.projectInit (/usr/local/lib/node_modules/serverless/lib/actions/ProjectInit.js:92:10)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:186:31
    at Array.reduce (native)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:185:32
From previous event:
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:183:12)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:429:20)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:398:38)
    at /usr/local/lib/node_modules/serverless/bin/serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3
```

and If I try "sls dash summary I get the following error
```
Serverless: 2 stages ------------------------------
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property 'getAllRegions' of undefined
    at Project.getAllRegions (/usr/local/lib/node_modules/serverless/lib/Project.js:241:38)
    at /usr/local/lib/node_modules/serverless/lib/actions/DashSummary.js:61:38
    at Array.forEach (native)
    at DashSummary.dashSummary (/usr/local/lib/node_modules/serverless/lib/actions/DashSummary.js:59:14)
From previous event:
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:186:31
    at Array.reduce (native)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:185:32
From previous event:
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:183:12)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:429:20)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:398:38)
    at /usr/local/lib/node_modules/serverless/bin/serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3
```

I'm not using any special packages or dependencies

**Comment by flomotlik** [comment]
Hi, thank you for reaching out to us! At this point we've stopped working on 0.5 of Serverless to fully focus on V1.0 that we're currently working on. Therefore we're not taking any changes for 0.5 and do not plan any future releases at this point. We only have a limited set of resources and just need to make sure we're putting everything we have into our next release (and can provide great long term support and backwards compatibility from then on). Hope you understand.

We would love to get your feedback on V1 of the framework and I'm happy to walk you through any questions to make sure its all working great for you.

**Comment by base2arthur** [comment]
Probably a little late but do this when you have project related problems
sls project init
