### ISSUE TITLE
localErrorHandlerData.handle is not a function

### ISSUE THREAD

**Issue by nick-zh** [serverless/serverless#10039]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

It seemed to work fine in `serverless:2.60.0` but in `2.60.2` when i have an error during deploy, i am getting:
```
serverless/lib/cli/handle-error.js:108
      localErrorHandlerData.handle(exception, localErrorHandlerData.options);
                            ^
TypeError: localErrorHandlerData.handle is not a function
```

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

sls deploy

### Command output

```shell
serverless/lib/cli/handle-error.js:108
      localErrorHandlerData.handle(exception, localErrorHandlerData.options);
                            ^
TypeError: localErrorHandlerData.handle is not a function
```

### Environment information

```shell
Framework Core: 2.60.2 (local)
Plugin: 5.4.5
SDK: 4.3.0
Components: 3.17.1
```

**Comment by medikoo** [comment]
@nick-zh great thanks for reporting. Fix will be issued shortly

**Comment by nick-zh** [comment]
Wow that was blazing fast, many thanks @medikoo :pray:
