### ISSUE TITLE
Cannot find module for any node_modules

### ISSUE THREAD

**Issue by smuffff** [serverless/serverless#1860]
When I use npm to install a package, I always get the following error when I require it in:

{
  "errorMessage": "Cannot find module 'jwt-simple'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:276:25)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)",
    "Object.<anonymous> (/var/task/handler.js:3:11)",
    "Module._compile (module.js:409:26)",
    "Object.Module._extensions..js (module.js:416:10)",
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)",
    "Module.require (module.js:353:17)"
  ]
}

The node_modules folder, and the normal serverless files (handler.js, serverless.yml etc) are all at the top level.

Interestingly - if I go into the aws lambda console and download the code it's uploaded, change the zip slightly (upload and then remove a random file) and then re-upload the code, it run's fine.

I guess it's an issue in the way that serverless creates the zip file, I'm running on a windows machine.

**Comment by smuffff** [comment]
I'm running on 1.0.0-beta.1.1.  Issue can be recreated by creating a new service, npm install a random package then simply require it at the top of handler.js

`var jwt = require('jwt-simple');

// Your first function handler
module.exports.hello = (event, context, cb) => cb(null,
  { message: 'Go Serverless v1.0! Your function executed successfully!', event }
);`

**Comment by bfhobbes** [comment]
I have the same issue. (Also running my machine from windows machine )
It was working fine with 1.0.0-beta.1, but broken in 1.0.0-beta.1.1

It appears to be an issue with folders, as I was also having an issue with it being unable to resolve
`require('./lib/somefile.js')`
But if I just move the file, then
`require('./somefile.js') works.`

The files are all present in the generated zip file.

**Comment by clauderic** [comment]
Same issue here

**Comment by bfhobbes** [comment]
jszip was incorrectly being passed UNIX as a host platform name. PR#1863 has a potential fix
