### ISSUE TITLE
this.userStats.track is not a function error when tailing function logs

### ISSUE THREAD

**Issue by ajkerr** [serverless/serverless#4434]
# Bug Report

## Description

After upgrading to 1.24.0, we are seeing an error when we run `serverless logs --stage myStage --function myFunction --tail`

For bug reports:
* What went wrong?

We get the following error message: "this.userStats.track is not a function", and serverless terminates rather than waiting for log events.

* What did you expect should have happened?

The log should be tailed.

## Additional Data

* ***Serverless Framework Version you're using***:
1.24.0
* ***Operating System***:
macOS 10.13.1
* ***Platform***:
AWS

Reverting to 1.23.0 fixes the issue.

**Comment by HyperBrain** [comment]
Hi @ajkerr , thanks for reporting the issue.

Can you execute the command with `SLS_DEBUG=*` set in the environment? This will show a complete stacktrace.

**Comment by ajkerr** [comment]
Sure thing, here is the stack trace:

```
TypeError: this.userStats.track is not a function
    at Logs.track (/usr/local/xps/xps-admin-serverless/node_modules/serverless/lib/plugins/logs/logs.js:59:22)
From previous event:
    at Object.after:logs:logs [as hook] (/usr/local/xps/xps-admin-serverless/node_modules/serverless/lib/plugins/logs/logs.js:50:53)
    at BbPromise.reduce (/usr/local/xps/xps-admin-serverless/node_modules/serverless/lib/classes/PluginManager.js:366:55)
From previous event:
    at PluginManager.invoke (/usr/local/xps/xps-admin-serverless/node_modules/serverless/lib/classes/PluginManager.js:366:22)
    at PluginManager.run (/usr/local/xps/xps-admin-serverless/node_modules/serverless/lib/classes/PluginManager.js:397:17)
    at variables.populateService.then (/usr/local/xps/xps-admin-serverless/node_modules/serverless/lib/Serverless.js:104:33)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at Serverless.run (/usr/local/xps/xps-admin-serverless/node_modules/serverless/lib/Serverless.js:91:74)
    at serverless.init.then (/usr/local/xps/xps-admin-serverless/node_modules/serverless/bin/serverless:42:50)
```

**Comment by horike37** [comment]
Today, I have done a workshop for the framework at ServerlessConf, and all attendees have faced the same problem with v1.24.0. The logs command would be broken by #4344 PR.
It looks a critical bug.

cc @serverless/framework-maintainers

**Comment by HyperBrain** [comment]
@horike37 We should try to get a 1.24.1 ready asap that fixes the issue, as this is (as you already stated) a critical one. The logs function is used by many people.

**Comment by HyperBrain** [comment]
I've changed the stage to accepted.

**Comment by ryanwmarsh** [comment]
Until this fix is released (1.24.1) is there a mitigation strategy?
